import Head from "next/head";
import Header from "../Components/Header";
import Footer from "../Components/Footer";
import Banner from "../Components/Banner";
import Features from "../Components/Features";
import Cards from "../Components/Cards";
import Team from "../Components/Team";
import Form from "../Components/form";
import NewsLetter from "../Components/NewsLetter";
import { useState, useEffect } from "react";
// import AppContext from "./AppContext";

export default function Home() {

  // if (!data) {
  //   console.log("no data yet");
  //   return <div>No data Yet</div>;
  // }

  return (
      <div>
        <Head>
          <title>FitPlus</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <script src="./TW-ELEMENTS-PATH/dist/js/index.min.js"></script>
        </Head>

        <Header />
        <div>
          <Banner />
          <Features />
          <Cards />
          <Team />
          <NewsLetter />
          <Form />
          <Footer />
        </div>
      </div>
    
  );
}
